# Generated by Django 5.0.3 on 2024-04-10 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='series',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.postcategory'),
        ),
    ]
