# Generated by Django 5.0.3 on 2024-04-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_post_series_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSeries',
        ),
    ]
